### ISSUE TITLE
206 content

### ISSUE THREAD

**Issue by hack-back** [keikurono/haarpcache#10]
hello,
thanks for this project its perfect,
but why it cant cache IDM downloads ?
i try to download video from fbcd 
and i try to download file from filehippo
if you start the download with IDM to leave it till finish, it open with one mirror and it cached fine.
but clients use IDM because they need more than one mirror while downloading,
so if we start the download then stop then start it , it continue downloading with more than one mirror but then it always miss and cant be cached,
can you solve this problem ?
IDM = Internet Download Manager.
now in this days all clients use IDM to download files because it give them full speed.
Thanks.

**Comment by keikurono** [comment]
It's not possible. The system works by downloading and storing the file into one. So if you have multiple threads for downloading the same file (code: 206), then only one is treated and the others are left out (bypassing).

This does not cause any problem for you if I'm not mistaken reading your message..

Regards.

**Comment by hack-back** [comment]
Okay, Thank you.
