### ISSUE TITLE
Some Explanations about the config File.

### ISSUE THREAD

**Issue by Degreane** [keikurono/haarpcache#12]
Hello Sir. 
Just need some explanations about haarp.conf 
for instance what does the following mean and how do they function.

ORKUT_NORESUME true
ORKUT_NODOWN true

also in transparent mode is it TProxy or just redirect ? 
if needed to achieve TProxy mode how is it done ? 

one more question . 
if for some reason the mysql database got corrupted and needed to be created or truncated data still on harddrive but does not respond as HIT from Haarp. is there a solution to tell Haarp process to read the harddrive cache file if present after determining the storage hash scheme and then afterwards check with mysql database. 
on heavy systems the database mysql is becoming a bottleneck.
isn't it better to use something like mongodb or tokyo cabinet/tyrant much much loose and more efficient than mysql ....

much regards

**Comment by keikurono** [comment]
The option ORKUT_xx is deprecated, because the plugin for the website orkut not exists. 
Haarpcache only work like a proxy, not Tproxy mode. The option transparent is in test.

"on heavy systems the database mysql is becoming a bottleneck.
isn't it better to use something like mongodb or tokyo cabinet/tyrant much much loose and more efficient than mysql ...."
Thanks for the feedback ...

**Comment by Degreane** [comment]
Hello,
Thanks for the explanation.

Regards

On Fri, Nov 27, 2015 at 8:53 AM, Kei Kurono <notifications@github.com>
wrote:

> The option ORKUT_xx is deprecated, because the plugin for the website
> orkut not exists.
> Haarpcache only work like a proxy, not Tproxy mode. The option transparent
> is in test.
>
> "on heavy systems the database mysql is becoming a bottleneck.
> isn't it better to use something like mongodb or tokyo cabinet/tyrant much
> much loose and more efficient than mysql ...."
> Thanks for the feedback ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keikurono/haarpcache/issues/12#issuecomment-160054946>
> .
>



-- 
============================
         Faysal Banna
 Meteorological Services
Rafic Harriri International Airport
      Beirut - Lebanon
    Mob: +961-3-258043
=============================
